name: Build wheels

on:
  workflow_dispatch:
    inputs:
      revision:
        description: Revision from psf/black to compile.
        required: true
        default: main

jobs:
  build:
    name: ${{ matrix.name }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: linux-x86_64

          - os: windows-2019
            name: windows-amd64

          - os: macos-11
            name: macos-x86_64
            macos_arch: "x86_64"

          - os: macos-11
            name: macos-arm64
            macos_arch: "arm64"

          - os: macos-11
            name: macos-universal2
            macos_arch: "universal2"

    steps:
      - name: Checkout requested revision of Black
        uses: actions/checkout@v3
        with:
          repository: psf/black
          ref: "${{ github.event.inputs.revision }}"
          path: "."
          # setuptools-scm needs the commit (or tag?) history to be able to determine
          # how a distribution should be versioned, and sadly I can't find a way to
          # do a treeless or blobless clone with actions/checkout ._.
          fetch-depth: 0

      - name: Print debug information
        run: git show HEAD --stat

      # This MUST go after the initial clone of Black or else it would first clean this
      # directory and this clone as well before cloning Black.
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          path: .mypyc-support

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Build wheels via cibuildwheel
        uses: pypa/cibuildwheel@v2.3.0
        env:
          CIBW_ARCHS_MACOS: "${{ matrix.macos_arch }}"
          CIBW_MANYLINUX_X86_64_IMAGE: 'quay.io/pypa/manylinux2014_x86_64:2021-11-20-f410d11'
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.6.2"

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}-wheels
          path: ./wheelhouse/*.whl
